# mkdocs.yml
site_name: Mon Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

# Configuration multi-langues/versions
extra:
  versions:
    - name: Arender 1
      link: /arender-1/
    - name: Arender 2
      link: /arender-2/

# Configuration pour GitHub Pages
site_url: https://firmin-kaman.github.io/mkdocs-test-2/
repo_url: https://github.com/firmin-kaman/mkdocs-test-2
repo_name: firmin-kaman/mkdocs-test-2

# Plugins
plugins:
  - search
  - git-revision-date
  - mike:
    alias: latest
    version_selector: true

# Structure de documentation
nav:
  - Accueil: index.md
  - Arender 1:
      - Présentation: arender-1/index.md
  - Arender 2:
      - Présentation: arender-2/index.md