name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      #- run: pip install mkdocs-material mkdocs-git-revision-date-plugin
      - run: pip install -r requirements.txt
      #- run: mkdocs gh-deploy --force
      - name: Get version from tag or generate
        id: version
        run: |
          if [ -n "$(git tag)" ]; then
            echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          else
            echo "version=0.0.1" >> $GITHUB_OUTPUT
          fi
          echo "Using version: ${{ steps.version.outputs.version }}"
      
      - name: Deploy with Mike
        run: |
          mike deploy --push --update-aliases ${{ steps.version.outputs.version }} latest
          mike set-default latest